Solve 02-components
js-tasks-ru/vue-20220616_anastasiya00 pull request #3
Opened 2022-06-25 15:00 UTC by Donor20

2022-06-25 15:01 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-06-25 17:34 UTC, ShGKme requested changes
В `02-components/01-CounterButtonComponent` требуется добавить опцию `emits`. Остальные задачи приняты.

2022-06-25 17:34 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  },
Компонент порождает событие `update:count`, но в компоненте не описано ни одно событие в `emits`. В этом компоненте отсутствие описания события не приводит к проблемам в его работе, но:
1. Описание событий - хорошая практика для машиночитаемого документирования компонента
2. Это и хорошая привычка, так как при совпадении имени события с нативным событием, обработчик сработает дважды.
3. Неописанные события также  попадают в `$attrs`, как нативное событие.

2022-06-27 16:45 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-06-27 19:06 UTC, ShGKme approved these changes
Принято 👍

2022-06-27 19:08 UTC, merged